name: Dynapyt

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"
      
      - name: Install dependencies
        run: |
          python -m pip install . && python -m pip install -r requirements_dev.txt && python -m pip install pytest

      - name: Instrument the Repository
        run: |
          python -m pip install pytest libcst dynapyt==0.1.0
          python -m dynapyt.run_instrumentation --directory tests/ --analysis CallGraph

      - name: Run the Analysis
        run: |
          echo 'import pytest; pytest.main(["--import-mode=importlib", "tests/"])' > run_tests_dynapyt.py
          python -m dynapyt.run_analysis --entry run_tests_dynapyt.py --analysis CallGraph
          ls -l dynapyt.json

      - name: Upload Dynapyt Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dynapyt-callgraph
          path: /home/runner/work/graph-012/graph-012/dynapyt.json
